version: "3.9"
services:
  f1_stream_selector:
    image: f1_stream_selector:latest
    container_name: f1_stream_selector
    ports:
        - "8080:8080"
    volumes:
        - /root/f1_stream_selector:/usr/src/app
    restart: unless-stopped